service: sls-food-backend
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: ap-southeast-1
  memorySize: 512
  timeout: 60
  endpointType: regional
  environment:
    FOOD_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  s3:
    food-security-csv:
      name: food-security-csv
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 'arn:aws:dynamodb:ap-southeast-1:*:*'
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource: 'arn:aws:s3:::*'
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:DeleteObject'
          Resource: 'arn:aws:s3:::food-security-csv/*'

resources:
  Resources:
    FoodTable:
      Type: AWS::DynamoDB::Table
      # DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.FOOD_TABLE}
        AttributeDefinitions:
          - AttributeName: PostalUnit
            AttributeType: S
          - AttributeName: Postal
            AttributeType: S
          - AttributeName: Programme
            AttributeType: S
          - AttributeName: Location
            AttributeType: S
        KeySchema:
          - AttributeName: PostalUnit
            KeyType: HASH
          - AttributeName: Postal
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: ProgrammeIndex
            KeySchema:
              - AttributeName: PostalUnit
                KeyType: HASH
              - AttributeName: Programme
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          - IndexName: ProgrammeGlobalIndex
            KeySchema:
              - AttributeName: Programme
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: LocationGlobalIndex
            KeySchema:
              - AttributeName: Location
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

functions:
  transformXlsxToCsv:
    handler: lambda/transformXlsxToCsv.handler
    memorySize: 10240
    events:
      - s3:
          bucket: food-security-csv
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${file(./config/bucketFolders.js):first}
            - suffix: .xlsx

  pushCsvToDynamoDb:
    handler: lambda/pushCsvToDynamoDb.handler
    events:
      - s3:
          bucket: food-security-csv
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${file(./config/bucketFolders.js):second}
            - suffix: .csv
