const sheetsConfig = {
  'Cooked Meals': {
    trimTopRows: 7,
    headers: [
      'no',
      'block',
      'unit',
      'roadName',
      'postalCode',
      'clientFullName',
      'clientContactNo',
      'yearOfBirth',
      'foodRecipientType',
      'numOfAdults',
      'numOfChildren',
      'startDate',
      'endDate',
      'regularity',
      'frequency',
      'days',
      'meals',
      'numOfDailyMealsRequired',
      'dietaryRestriction',
      'dietarySpecificRequirements',
      'additionalDietaryRemarks',
      'deliveryMode',
      'addressOfDistributionPoint',
      'pocName',
      'pocContact',
      'foodRequestorName',
      'foodProviderName',
      'programmeName',
      'updatedAsOf',
      'dataSource',
    ],
  },
  'Food Rations, Fresh Produce': {
    trimTopRows: 7,
    headers: [
      'no',
      'block',
      'unit',
      'roadName',
      'postalCode',
      'clientFullName',
      'clientContactNo',
      'yearOfBirth',
      'foodRecipientType',
      'numOfAdults',
      'numOfChildren',
      'regularity',
      'frequency',
      'additionalFrequencyRemarks',
      'numOfFoodRationsProvided',
      'dietaryRestriction',
      'dietarySpecificRequirements',
      'typeOfFoodRationsProvided',
      'additionalDietaryRemarks',
      'deliveryMode',
      'addressOfDistributionPoint',
      'pocName',
      'pocContact',
      'foodRequestorName',
      'foodProviderName',
      'programmeName',
      'updatedAsOf',
      'dataSource',
    ],
  },
};

module.exports = sheetsConfig;
